-- This is a list of all the RF.servers. It is much much easier to keep it all in here --

local RF = select(2, ...)
RF.servers = {}
RF.servers.na_nyc = {
    "AeriePeak",
    "AltarofStorms",
    "AlteracMountains",
    "Andorhal",
    "Anetheron",
    "Anvilmar",
    "Archimonde",
    "Area52",
    "Arygos",
    "Auchindoun",
    "Azuremyst",
    "BlackDragonflight",
    "BlackwingLair",
    "BladesEdge",
    "BloodFurnace",
    "Coilfang",
    "Dalaran",
    "Dalvengyr",
    "Dawnbringer",
    "Deathwing",
    "DemonSoul",
    "Dentarg",
    "Doomhammer",
    "Duskwood",
    "Executus",
    "Exodar",
    "Fizzcrank",
    "Galakrond",
    "Ghostlands",
    "Gnomeregan",
    "GrizzlyHills",
    "Haomarush",
    "Icecrown",
    "Jaedenar",
    "KelThuzad",
    "Khadgar",
    "Lethon",
    "MalGanis",
    "Norgannon",
    "Onyxia",
    "Scilla",
    "Sentinels",
    "ShatteredHalls",
    "SteamwheedleCartel",
    "Tanaris",
    "Terokkar",
    "TheScryers",
    "TheUnderbog",
    "TheVentureCo",
    "Thrall",
    "Turalyon",
    "Uldaman",
    "Undermine",
    "Velen",
    "Ysera",
    "Ysondre",
    "Zangarmarsh",
    "Zuluhed"
}

RF.servers.na_chicago = {
    "Agamaggan",
    "Aggramar",
    "Alexstrasza",
    "Alleria",
    "ArgentDawn",
    "Arthas",
    "Azgalor",
    "Azshara",
    "Baelgun",
    "Balnazzar",
    "Blackhand",
    "BleedingHollow",
    "Bloodhoof",
    "BurningBlade",
    "BurningLegion",
    "Chogall",
    "DarkIron",
    "Destromath",
    "Dethecus",
    "Detheroc",
    "Durotan",
    "EarthenRing",
    "Elune",
    "EmeraldDream",
    "Eonar",
    "Eredar",
    "Garona",
    "Gilneas",
    "Gorefiend",
    "Gorgonnash",
    "Greymane",
    "Hellscream",
    "Illidan",
    "Kaelthas",
    "Kalecgos",
    "Kargath",
    "KirinTor",
    "LaughingSkull",
    "Lightninghoof",
    "LightningsBlade",
    "Llane",
    "Lothar",
    "Madoran",
    "Maelstrom",
    "Magtheridon",
    "Malfurion",
    "Malygos",
    "Mannoroth",
    "Medivh",
    "Moonrunner",
    "Nazjatar",
    "Ravencrest",
    "Sargeras",
    "Shadowmoon",
    "ShatteredHand",
    "Skullcrusher",
    "Spinebreaker",
    "Staghelm",
    "Stormrage",
    "Stormreaver",
    "Thunderhorn",
    "Thunderlord",
    "Trollbane",
    "TwistingNether",
    "Ursin",
    "Warsong",
    "Whisperwind",
    "Wildhammer",
    "Zuljin"
}

RF.servers.na_phoenix = {
    "Antonidas",
    "Anubarak",
    "BlackwaterRaiders",
    "Bladefist",
    "BoreanTundra",
    "Cairne",
    "CenarionCircle",
    "Cenarius",
    "Darrowmere",
    "DrakTharon",
    "Drenden",
    "EchoIsles",
    "Farstriders",
    "Fenris",
    "Garrosh",
    "Hydraxis",
    "Hyjal",
    "Korialstrasz",
    "Lightbringer",
    "Maiev",
    "Misha",
    "MokNathal",
    "MoonGuard",
    "Nazgrel",
    "Nesingwary",
    "Nordrassil",
    "Queldorei",
    "Ranveholdt",
    "Rivendare",
    "Shandris",
    "Shuhalo",
    "SistersofElune",
    "TheForgottenCoast",
    "Tortheldrin",
    "Uther",
    "Vashj",
    "Winterhoof",
    "WyrmrestAccord"
}

RF.servers.na_la = {
    "Aegwynn",
    "Akama",
    "Arathor",
    "AzjolNerub",
    "Blackrock",
    "Bloodscalp",
    "Bonechewer",
    "Boulderfist",
    "Bronzebeard",
    "Chromaggus",
    "Crushridge",
    "Daggerspine",
    "Darkspear",
    "Draenor",
    "Dragonblight",
    "Dragonmaw",
    "Draka",
    "Drakthul",
    "Dunemaul",
    "Eitrigg",
    "EldreThalas",
    "Feathermoon",
    "Firetree",
    "Frostmane",
    "Frostwolf",
    "Garithos",
    "Gundrak",
    "Gurubashi",
    "Hakkar",
    "KhazModan",
    "Kiljaeden",
    "Kilrogg",
    "Korgath",
    "KulTiras",
    "Malorne",
    "Mugthol",
    "Muradin",
    "Nathrezim",
    "Nerzhul",
    "Perenolde",
    "Proudmoore",
    "Rexxar",
    "Runetotem",
    "ScarletCrusade",
    "Senjin",
    "ShadowCouncil",
    "Shadowsong",
    "SilverHand",
    "Sivlermoon",
    "Skywall",
    "Smolderthorn",
    "Spirestone",
    "Stonemaul",
    "Stormscale",
    "Suramar",
    "Terenas",
    "ThoriumBrotherhood",
    "Tichondrius",
    "Uldum",
    "Veknilash",
    "Windrunner"
}

RF.servers.br_realms = {
    "Azralon",
    "Nemesis",
    "Goldrinn",
    "TolBarad",
    "Gallywix"
}

RF.servers.la_realms = {
    "QuelThalas",
    "Drakkari",
    "Ragnaros"
}

RF.servers.oc_realms = {
    "AmanThul",
    "Barthilas",
    "Caelestrasz",
    "DathRemar",
    "Dreadmaul",
    "Frostmourne",
    "Gundrak",
    "JubeiThos",
    "Khazgoroth",
    "Nagrand",
    "Saurfang",
    "Thaurissan",
}

RF.servers.eu_en_realms = {
    "KulTiras",
    "Alonsus",
    "Anachronos",
    "Bronzebeard",
    "AeriePeak",
    "BladesEdge",
    "Veknilash",
    "Eonar",
    "Wildhammer",
    "Thunderhorn",
    "Kilrogg",
    "Runetotem",
    "Nagrand",
    "Aggramar",
    "Hellscream",
    "Hellfire",
    "Arathor",
    "AzjolNerub",
    "QuelThalas",
    "Ghostlands",
    "Dragonblight",
    "Darkspear",
    "Terokkar",
    "Saurfang",
    "Aszune",
    "Shadowsong",
    "Khadgar",
    "Bloodhoof",
    "BronzeDragonflight",
    "Nordrassil",
    "Lightbringer",
    "Mazrigos",
    "Azuremyst",
    "Stormrage",
    "Doomhammer",
    "Turalyon",
    "EmeraldDream",
    "Terenas",
    "Korgall",
    "Bloodfeather",
    "Executus",
    "BurningSteppes",
    "ShatteredHand",
    "ShatteredHalls",
    "Balnazzar",
    "AhnQiraj",
    "Trollbane",
    "Talnivarr",
    "Chromaggus",
    "Boulderfist",
    "Daggerspine",
    "LaughingSkull",
    "Sunstrider",
    "Emeriss",
    "Agamaggan",
    "Hakkar",
    "Crushridge",
    "Bloodscalp",
    "TwilightsHammer",
    "GrimBatol",
    "Aggra",
    "Karazhan",
    "LightningsBlade",
    "Deathwing",
    "TheMaesltrom",
    "Auchindoun",
    "Dunemaul",
    "Jaedenar",
    "Dragonmaw",
    "Spinebreaker",
    "Haomarush",
    "Vashj",
    "Stormreaver",
    "Zenedar",
    "Bladefist",
    "Frostwhisper",
    "Xavius",
    "Skullcrusher",
    "AlAkir",
    "Darksorrow",
    "Genjuros",
    "Neptulon",
    "Drakthul",
    "BurningBlade",
    "Dentarg",
    "TarrenMill",
    "Moonglade",
    "TheShatar",
    "SteamwheedleCartel",
    "DarkmoonFaire",
    "EarthenRing",
    "ScarshieldLegion",
    "Ravenholdt",
    "TheVentureCo",
    "Sporeggar",
    "DefiasBrotherhood",
}

RF.servers.eu_fr_realms = {
    "Chantséternels",
    "Voljin",
    "Elune",
    "Varimathras",
    "MarécagedeZangar",
    "Dalaran",
    "Eitrigg",
    "Krasus",
    "Suramar",
    "Medivh",
    "Uldaman",
    "DrekThar",
    "Arakarahm",
    "ThrokFeroth",
    "Rashgarroth",
    "KaelThas",
    "Naxxramas",
    "Arathi",
    "TemplerNoir",
    "Illidan",
    "Sargeras",
    "Garona",
    "Nerzhul",
    "EldreThalas",
    "Chogall",
    "Sinstralis",
    "ConfrerieduThorium",
    "LesClairvoyants",
    "LesSentinelles",
    "LaCroisadeécarlate",
    "CultedelaRivenoire",
    "ConseildesOmbres",
}

RF.servers.eu_de_realms = {
    "Gilneas",
    "Ulduar",
    "Garrosh",
    "Shattrath",
    "Nozdormu",
    "Nethersturm",
    "Alextrasza",
    "UnGoro",
    "Area52",
    "Senjin",
    "Ambossar",
    "Kargath",
    "Ysera",
    "Malorne",
    "Malygos",
    "Malfurion",
    "Tichondrius",
    "Lordaeron",
    "Arygos",
    "KhazGoroth",
    "Teldrassil",
    "Perenolde",
    "Durotan",
    "Tirion",
    "Lothar",
    "Baelgun",
    "Norgannon",
    "DunMorogh",
    "Rexxar",
    "Alleria",
    "Proudmoore",
    "Madmortem",
    "Nazjatar",
    "Dalvengyr",
    "Frostmourne",
    "Zuluhed",
    "Anubarak",
    "Arthas",
    "Veklor",
    "Blutkessel",
    "KelThuzad",
    "Wrathbringer",
    "Dethecus",
    "Terrordar",
    "Mugthol",
    "Theradras",
    "Onyxia",
    "Echsenkessel",
    "Taerar",
    "MalGanas",
    "Anetheron",
    "FestungderStürme",
    "Rajaxx",
    "Guldan",
    "Nathrezim",
    "Kiljaeden",
    "Nefarian",
    "Nerathor",
    "Mannoroth",
    "Destromath",
    "Gorgonnash",
    "Azshara",
    "Kragjin",
    "DieewigeWacht",
    "DieSilberneHand",
    "Todeswache",
    "ZirkeldesCenarius",
    "DerMithrilorden",
    "DerRatvonDalaran",
    "Forscherliga",
    "DieNachtwache",
    "DieArguswacht",
    "DieTodeskrallen",
    "DasSyndikat",
    "DerAbyssischeRat",
    "KultderVerdammten",
    "DasKonsortium",
}

RF.servers.eu_es_realms = {
    "Exodar",
    "Minahonda",
    "ColinasPardas",
    "Tyrande",
    "LosErrantes",
    "Zuljin",
    "Sanguino",
    "Shendralar",
    "Uldum",
}

RF.servers.eu_ru_realms = {
    "Подземье",
    "Разувий",
    "Корольлич",
    "Седогрив",
    "Пиратскаябухта",
    "Ткачсмерти",
    "Гром",
    "Термоштепсел",
}

RF.servers.eu_it_realms = {
    "WellofEternity",
    "Nemsis",
}

---- Posts ----
RF.posts = {}
-- NA posts
RF.posts.na_post = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4NA|r Server"
RF.posts.oc_post = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4OC|r Server"
RF.posts.br_post = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4BR|r Server"
RF.posts.la_post = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4LA|r Server"

-- EU posts
RF.posts.en_post = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4EN|r Server"
RF.posts.de_post = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4DE|r Server"
RF.posts.fr_post = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4FR|r Server"
RF.posts.it_post = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4IT|r Server"
RF.posts.ru_post = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4RU|r Server"
RF.posts.es_post = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4ES|r Server"

---- Categorisation Strings ----
-- These are used to differentiate the NA data centres.
-- Other locations just use their own label
RF.cat = {}
RF.cat.home = 'HOME'
RF.cat.na_nyc_id = 'NA-NYC'
RF.cat.na_la_id = 'NA-LA'
RF.cat.na_phoenix_id = 'NA-PHX'
RF.cat.na_chicago_id = 'NA-CHI'