-- This is a list of all the RF.servers. It is much much easier to keep it all in here --

local RF = select(2, ...)
RF.servers = {}
local na_nyc = {"NA", "NYC"}
local na_chi = {"NA", "CHI"}
local na_phx = {"NA", "PHX"}
local na_la = {"NA", "LA"}
local br = {"BR", "nil"}
local la = {"LA", "nil"}
local oc = {"OC", "nil"}

RF.servers = {
    -- North America: New York City
    AeriePeak = na_nyc,
    AltarofStorms = na_nyc,
    AlteracMountains = na_nyc,
    Andorhal = na_nyc,
    Anetheron = na_nyc,
    Anvilmar = na_nyc,
    Archimonde = na_nyc,
    Area52 = na_nyc,
    Arygos = na_nyc,
    Auchindoun = na_nyc,
    Azuremyst = na_nyc,
    BlackDragonflight = na_nyc,
    BlackwingLair = na_nyc,
    BladesEdge = na_nyc,
    BloodFurnace = na_nyc,
    Coilfang = na_nyc,
    Dalaran = na_nyc,
    Dalvengyr = na_nyc,
    Dawnbringer = na_nyc,
    Deathwing = na_nyc,
    DemonSoul = na_nyc,
    Dentarg = na_nyc,
    Doomhammer = na_nyc,
    Duskwood = na_nyc,
    Executus = na_nyc,
    Exodar = na_nyc,
    Fizzcrank = na_nyc,
    Galakrond = na_nyc,
    Ghostlands = na_nyc,
    Gnomeregan = na_nyc,
    GrizzlyHills = na_nyc,
    Haomarush = na_nyc,
    Icecrown = na_nyc,
    Jaedenar = na_nyc,
    KelThuzad = na_nyc,
    Khadgar = na_nyc,
    Lethon = na_nyc,
    MalGanis = na_nyc,
    Norgannon = na_nyc,
    Onyxia = na_nyc,
    Scilla = na_nyc,
    Sentinels = na_nyc,
    ShatteredHalls = na_nyc,
    SteamwheedleCartel = na_nyc,
    Tanaris = na_nyc,
    Terokkar = na_nyc,
    TheScryers = na_nyc,
    TheUnderbog = na_nyc,
    TheVentureCo = na_nyc,
    Thrall = na_nyc,
    Turalyon = na_nyc,
    Uldaman = na_nyc,
    Undermine = na_nyc,
    Velen = na_nyc,
    Ysera = na_nyc,
    Ysondre = na_nyc,
    Zangarmarsh = na_nyc,
    Zuluhed = na_nyc,
    -- North America: Chicago
    Agamaggan = na_chi,
    Aggramar = na_chi,
    Alexstrasza = na_chi,
    Alleria = na_chi,
    ArgentDawn = na_chi,
    Arthas = na_chi,
    Azgalor = na_chi,
    Azshara = na_chi,
    Baelgun = na_chi,
    Balnazzar = na_chi,
    Blackhand = na_chi,
    BleedingHollow = na_chi,
    Bloodhoof = na_chi,
    BurningBlade = na_chi,
    BurningLegion = na_chi,
    Chogall = na_chi,
    DarkIron = na_chi,
    Destromath = na_chi,
    Dethecus = na_chi,
    Detheroc = na_chi,
    Durotan = na_chi,
    EarthenRing = na_chi,
    Elune = na_chi,
    EmeraldDream = na_chi,
    Eonar = na_chi,
    Eredar = na_chi,
    Garona = na_chi,
    Gilneas = na_chi,
    Gorefiend = na_chi,
    Gorgonnash = na_chi,
    Greymane = na_chi,
    Guldan = na_chi,
    Hellscream = na_chi,
    Illidan = na_chi,
    Kaelthas = na_chi,
    Kalecgos = na_chi,
    Kargath = na_chi,
    KirinTor = na_chi,
    LaughingSkull = na_chi,
    Lightninghoof = na_chi,
    LightningsBlade = na_chi,
    Llane = na_chi,
    Lothar = na_chi,
    Madoran = na_chi,
    Maelstrom = na_chi,
    Magtheridon = na_chi,
    Malfurion = na_chi,
    Malygos = na_chi,
    Mannoroth = na_chi,
    Medivh = na_chi,
    Moonrunner = na_chi,
    Nazjatar = na_chi,
    Ravencrest = na_chi,
    Sargeras = na_chi,
    Shadowmoon = na_chi,
    ShatteredHand = na_chi,
    Skullcrusher = na_chi,
    Spinebreaker = na_chi,
    Staghelm = na_chi,
    Stormrage = na_chi,
    Stormreaver = na_chi,
    Thunderhorn = na_chi,
    Thunderlord = na_chi,
    Trollbane = na_chi,
    TwistingNether = na_chi,
    Ursin = na_chi,
    Warsong = na_chi,
    Whisperwind = na_chi,
    Wildhammer = na_chi,
    Zuljin = na_chi,
    -- North America: Phoenix
    Antonidas = na_phx,
    Anubarak = na_phx,
    BlackwaterRaiders = na_phx,
    Bladefist = na_phx,
    BoreanTundra = na_phx,
    Cairne = na_phx,
    CenarionCircle = na_phx,
    Cenarius = na_phx,
    Darrowmere = na_phx,
    DrakTharon = na_phx,
    Drenden = na_phx,
    EchoIsles = na_phx,
    Farstriders = na_phx,
    Fenris = na_phx,
    Garrosh = na_phx,
    Hydraxis = na_phx,
    Hyjal = na_phx,
    Korialstrasz = na_phx,
    Lightbringer = na_phx,
    Maiev = na_phx,
    Misha = na_phx,
    MokNathal = na_phx,
    MoonGuard = na_phx,
    Nazgrel = na_phx,
    Nesingwary = na_phx,
    Nordrassil = na_phx,
    Queldorei = na_phx,
    Ravenholdt = na_phx,
    Rivendare = na_phx,
    Shandris = na_phx,
    Shuhalo = na_phx,
    SistersofElune = na_phx,
    TheForgottenCoast = na_phx,
    Tortheldrin = na_phx,
    Uther = na_phx,
    Vashj = na_phx,
    Winterhoof = na_phx,
    WyrmrestAccord = na_phx,
    -- North America: Los Angeles
    Aegwynn = na_la,
    Akama = na_la,
    Arathor = na_la,
    AzjolNerub = na_la,
    Blackrock = na_la,
    Bloodscalp = na_la,
    Bonechewer = na_la,
    Boulderfist = na_la,
    Bronzebeard = na_la,
    Chromaggus = na_la,
    Crushridge = na_la,
    Daggerspine = na_la,
    Darkspear = na_la,
    Draenor = na_la,
    Dragonblight = na_la,
    Dragonmaw = na_la,
    Draka = na_la,
    Drakthul = na_la,
    Dunemaul = na_la,
    Eitrigg = na_la,
    EldreThalas = na_la,
    Feathermoon = na_la,
    Firetree = na_la,
    Frostmane = na_la,
    Frostwolf = na_la,
    Garithos = na_la,
    Gurubashi = na_la,
    Hakkar = na_la,
    KhazModan = na_la,
    Kiljaeden = na_la,
    Kilrogg = na_la,
    Korgath = na_la,
    KulTiras = na_la,
    Malorne = na_la,
    Mugthol = na_la,
    Muradin = na_la,
    Nathrezim = na_la,
    Nerzhul = na_la,
    Perenolde = na_la,
    Proudmoore = na_la,
    Rexxar = na_la,
    Runetotem = na_la,
    ScarletCrusade = na_la,
    Senjin = na_la,
    ShadowCouncil = na_la,
    Shadowsong = na_la,
    SilverHand = na_la,
    Sivlermoon = na_la,
    Skywall = na_la,
    Smolderthorn = na_la,
    Spirestone = na_la,
    Stonemaul = na_la,
    Stormscale = na_la,
    Suramar = na_la,
    Terenas = na_la,
    ThoriumBrotherhood = na_la,
    Tichondrius = na_la,
    Uldum = na_la,
    Veknilash = na_la,
    Windrunner = na_la,
    -- Brazillian
    Azralon = br,
    Nemesis = br,
    Goldrinn = br,
    TolBarad = br,
    Gallywix = br,

    -- Latin America
    QuelThalas = la,
    Drakkari = la,
    Ragnaros = la,
    -- Oceanic
    AmanThul = oc,
    Barthilas = oc,
    Caelestrasz = oc,
    DathRemar = oc,
    Dreadmaul = oc,
    Frostmourne = oc,
    Gundrak = oc,
    JubeiThos = oc,
    Khazgoroth = oc,
    Nagrand = oc,
    Saurfang = oc,
    Thaurissan = oc
}

---- Posts ----
RF.posts = {}
-- NA posts
RF.posts.na_nyc_post     = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4NA-NYC|r Server"
RF.posts.na_la_post      = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4NA-LA|r Server"
RF.posts.na_chicago_post = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4NA-CHI|r Server"
RF.posts.na_phoenix_post = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4NA-PHX|r Server"
RF.posts.oc_post = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4OC|r Server"
RF.posts.br_post = "|cff00ffff[Region Filter]:|r You are an on a |cffFF6EB4BR|r Server"
RF.posts.la_post = "|cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4LA|r Server"

---- Categorisation Strings ----
-- These are used to differentiate the data centres and regions in the text labels for each LFG entry
RF.cat = {}
RF.cat.home = 'HOME'
RF.cat.na_nyc_id = 'NA-NYC'
RF.cat.na_la_id = 'NA-LA'
RF.cat.na_phx_id = 'NA-PHX'
RF.cat.na_chi_id = 'NA-CHI'
RF.cat.br = 'BR'
RF.cat.la = 'LA'
RF.cat.oc = 'OC'

-- -- EU posts
-- RF.posts.en_post = |cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4EN|r Server
-- RF.posts.de_post = |cff00ffff[Region Filter]:|r You are an on a |cffFF6EB4DE|r Server
-- RF.posts.fr_post = |cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4FR|r Server
-- RF.posts.it_post = |cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4IT|r Server
-- RF.posts.ru_post = |cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4RU|r Server
-- RF.posts.es_post = |cff00ffff[Region Filter]:|r You are an on an |cffFF6EB4ES|r Server

-- RF.servers.eu_en_realms = {
--     KulTiras,
--     Alonsus,
--     Anachronos,
--     Bronzebeard,
--     AeriePeak,
--     BladesEdge,
--     Veknilash,
--     Eonar,
--     Wildhammer,
--     Thunderhorn,
--     Kilrogg,
--     Runetotem,
--     Nagrand,
--     Aggramar,
--     Hellscream,
--     Hellfire,
--     Arathor,
--     AzjolNerub,
--     QuelThalas,
--     Ghostlands,
--     Dragonblight,
--     Darkspear,
--     Terokkar,
--     Saurfang,
--     Aszune,
--     Shadowsong,
--     Khadgar,
--     Bloodhoof,
--     BronzeDragonflight,
--     Nordrassil,
--     Lightbringer,
--     Mazrigos,
--     Azuremyst,
--     Stormrage,
--     Doomhammer,
--     Turalyon,
--     EmeraldDream,
--     Terenas,
--     Korgall,
--     Bloodfeather,
--     Executus,
--     BurningSteppes,
--     ShatteredHand,
--     ShatteredHalls,
--     Balnazzar,
--     AhnQiraj,
--     Trollbane,
--     Talnivarr,
--     Chromaggus,
--     Boulderfist,
--     Daggerspine,
--     LaughingSkull,
--     Sunstrider,
--     Emeriss,
--     Agamaggan,
--     Hakkar,
--     Crushridge,
--     Bloodscalp,
--     TwilightsHammer,
--     GrimBatol,
--     Aggra,
--     Karazhan,
--     LightningsBlade,
--     Deathwing,
--     TheMaesltrom,
--     Auchindoun,
--     Dunemaul,
--     Jaedenar,
--     Dragonmaw,
--     Spinebreaker,
--     Haomarush,
--     Vashj,
--     Stormreaver,
--     Zenedar,
--     Bladefist,
--     Frostwhisper,
--     Xavius,
--     Skullcrusher,
--     AlAkir,
--     Darksorrow,
--     Genjuros,
--     Neptulon,
--     Drakthul,
--     BurningBlade,
--     Dentarg,
--     TarrenMill,
--     Moonglade,
--     TheShatar,
--     SteamwheedleCartel,
--     DarkmoonFaire,
--     EarthenRing,
--     ScarshieldLegion,
--     Ravenholdt,
--     TheVentureCo,
--     Sporeggar,
--     DefiasBrotherhood,
-- }

-- RF.servers.eu_fr_realms = {
--     Chantséternels,
--     Voljin,
--     Elune,
--     Varimathras,
--     MarécagedeZangar,
--     Dalaran,
--     Eitrigg,
--     Krasus,
--     Suramar,
--     Medivh,
--     Uldaman,
--     DrekThar,
--     Arakarahm,
--     ThrokFeroth,
--     Rashgarroth,
--     KaelThas,
--     Naxxramas,
--     Arathi,
--     TemplerNoir,
--     Illidan,
--     Sargeras,
--     Garona,
--     Nerzhul,
--     EldreThalas,
--     Chogall,
--     Sinstralis,
--     ConfrerieduThorium,
--     LesClairvoyants,
--     LesSentinelles,
--     LaCroisadeécarlate,
--     CultedelaRivenoire,
--     ConseildesOmbres,
-- }

-- RF.servers.eu_de_realms = {
--     Gilneas,
--     Ulduar,
--     Garrosh,
--     Shattrath,
--     Nozdormu,
--     Nethersturm,
--     Alextrasza,
--     UnGoro,
--     Area52,
--     Senjin,
--     Ambossar,
--     Kargath,
--     Ysera,
--     Malorne,
--     Malygos,
--     Malfurion,
--     Tichondrius,
--     Lordaeron,
--     Arygos,
--     KhazGoroth,
--     Teldrassil,
--     Perenolde,
--     Durotan,
--     Tirion,
--     Lothar,
--     Baelgun,
--     Norgannon,
--     DunMorogh,
--     Rexxar,
--     Alleria,
--     Proudmoore,
--     Madmortem,
--     Nazjatar,
--     Dalvengyr,
--     Frostmourne,
--     Zuluhed,
--     Anubarak,
--     Arthas,
--     Veklor,
--     Blutkessel,
--     KelThuzad,
--     Wrathbringer,
--     Dethecus,
--     Terrordar,
--     Mugthol,
--     Theradras,
--     Onyxia,
--     Echsenkessel,
--     Taerar,
--     MalGanas,
--     Anetheron,
--     FestungderStürme,
--     Rajaxx,
--     Guldan,
--     Nathrezim,
--     Kiljaeden,
--     Nefarian,
--     Nerathor,
--     Mannoroth,
--     Destromath,
--     Gorgonnash,
--     Azshara,
--     Kragjin,
--     DieewigeWacht,
--     DieSilberneHand,
--     Todeswache,
--     ZirkeldesCenarius,
--     DerMithrilorden,
--     DerRatvonDalaran,
--     Forscherliga,
--     DieNachtwache,
--     DieArguswacht,
--     DieTodeskrallen,
--     DasSyndikat,
--     DerAbyssischeRat,
--     KultderVerdammten,
--     DasKonsortium,
-- }

-- RF.servers.eu_es_realms = {
--     Exodar,
--     Minahonda,
--     ColinasPardas,
--     Tyrande,
--     LosErrantes,
--     Zuljin,
--     Sanguino,
--     Shendralar,
--     Uldum,
-- }

-- RF.servers.eu_ru_realms = {
--     Подземье,
--     Разувий,
--     Корольлич,
--     Седогрив,
--     Пиратскаябухта,
--     Ткачсмерти,
--     Гром,
--     Термоштепсел,
-- }

-- RF.servers.eu_it_realms = {
--     WellofEternity,
--     Nemsis,
-- }